//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAvaliacaoP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_consulta
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data_consulta { get; set; }
        public string observacao { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_clinica { get; set; }
        public Nullable<int> id_medico { get; set; }
    
        public virtual tb_clinica tb_clinica { get; set; }
        public virtual tb_medico tb_medico { get; set; }
        public virtual tb_paciente tb_paciente { get; set; }
    }
}
